name: "LtC Term Issue"
description: "Issue associated with a term that are either normative or non-normative"
title: "LtC Term Issue: [Term Name]"
labels: ["Public Review:Term", "PublicReview"]
assignees:
  - ben-norton
body:
- type: markdown
  attributes:
    value: |
      <div style="background-color: rgb(50, 50, 50); padding: 10px;">
      <h3><strong>Please read!</strong></h3>
      Please use the appropriate template for your issue according to the following guide:<br>
      1. If you have a general <strong>QUESTION</strong>, please visit the <a href="https://github.com/tdwg/ltc/discussions">LtC Discussions</a><br>
      2. If your issue is related to a specific <strong>TERM</strong>, you're in the right place!<br>
      3. If your issue is related to the <strong>WIKI</strong>, please use the Wiki Issue Template: <a href="https://github.com/tdwg/ltc/issues/new?template=ltc-wiki-pr-template.md">Wiki Issue</a><br>
      </div>
- type: input
  id: submitter
  attributes:
    label: Submitter
    description: "Please enter your name (preferably with your GitHub tag @name). If an issue is submitted on someone's behalf, please enter both names."
    placeholder: "Example:  Ben Norton (@ben-norton)"
- type: markdown
  attributes:
    value: |
      ## Issue Logistics
- type: dropdown
  id: issueType
  attributes:
    label:  Type of Issue
    description: Please select the nature of your issue.
    multiple: true
    options:
      - Enchancement
      - Error
      - General Issue
      - Improvement
      - Question
  validations:
    required: false
- type: dropdown
  id: action
  attributes: 
    label: Suggested Action 
    description: Please select the type of action associated with your issue
    options: 
      - Addition
      - Removal
      - Revision/Change
      - Other
- type: textarea
  id: justification
  attributes: 
    label: "Justification"
    description: "Please describe why this change is necessary." 
- type: markdown
  attributes:
    value: |
      ## Term
- type: dropdown
  id: termType
  attributes:
    label: Term Type
    description: Please enter the type of term associated with your issue 
    options: 
      - Class
      - Property
      - Other    
- type: input
  id: termName
  attributes:
    label: Term
    description: Term name (in lowerCamelCase for properties, UpperCamelCase for classes)
- type: input
  id: termIdentifier
  attributes:
    label: Term Identifier
    description: Please enter the term identifier (uri) associated with your issue
- type: markdown
  attributes:
    value: |
      ## Issue
- type: textarea
  id: issueDescription
  attributes:
    label: Description
    description: Please describe the issue
  validations:
    required: true  
- type: textarea
  id: comments
  attributes:
    label: Additional Comments
    description: Please enter any additional comments not captured in previous form fields      
